directories:
  output: release
  buildResources: build
appId: com.yamu.player
productName: YAMU
copyright: Copyright © 2024
files:
  - filter:
      - dist/**/*
      - main.js
      - preload.js
      - package.json
      - icon.ico
win:
  target: nsis
  icon: icon.ico
  artifactName: YAMU-Setup-${version}.exe
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  shortcutName: YAMU
electronVersion: 28.3.3
